#!/usr/bin/env python3
import jupyterhub.handlers.pages as pages
import jupyterhub.handlers.base as base
from jupyterhub import app
from everware import HomeHandler, SpawnHandler, UserSpawnHandler
import sys

handlers_map = {
    pages.HomeHandler: HomeHandler,
    pages.SpawnHandler: SpawnHandler,
    base.UserSpawnHandler: UserSpawnHandler
}


class Everware(app.JupyterHub):
    name = 'everware'

    def init_handlers(self):
        super().init_handlers()
        for i, cur_handler in enumerate(self.handlers):
            new_handler = handlers_map.get(cur_handler[1])
            if new_handler:
                cur_handler = list(cur_handler)
                cur_handler[1] = new_handler
                self.handlers[i] = tuple(cur_handler)


main = Everware.launch_instance

if __name__ == "__main__":
    main(sys.argv)
